### ISSUE TITLE
bug: fixed path of coco 128

### ISSUE THREAD

**Issue by znsoftm** [zhangming8/yolox-pytorch#2]
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 212, in main
    train_loader, val_loader = get_dataloader(opt, no_aug=no_aug)
  File "/home/znsoft/yolox-pytorch/data/coco_dataset.py", line 18, in get_dataloader
    train_dataset = COCODataset(data_dir=opt.data_dir,
  File "/home/znsoft/yolox-pytorch/data/datasets/coco.py", line 49, in __init__
    assert os.path.isfile(json_file), 'cannot find {}'.format(json_file)
AssertionError: cannot find /data/dataset/coco_dataset/annotations/instances_train2017.json

I have changed the coco path to /mnt/d/coco_obj , it still complains a wrong path.

**Comment by zhangming8** [comment]
You still using my dataset path. Maybe, you not modify 'dataset_path' to "/mnt/d/coco_obj" in "train.sh"

**Comment by znsoftm** [comment]
如果在train.sh中可以指定数据集位置，那是不是就不要在config.py中再加了？

还有上次说的，建议类别从数据中读取，不要写死在config.py中，毕竟正常训练的数据肯定不是coco原生的，否则训练的意义不大

**Comment by zhangming8** [comment]
嗯，在*.sh中传入的参数会替换掉opt.xxx里面的参数
